<MenuButton@Button>:
	font_size: 30
	size_hint: 0.2,0.1


<MainLayout>:
	canvas.after:
		Color:
			rgba: 0,0,0,0
		Rectangle:
			size: self.size
			pos: self.pos

    Button:
		text: ""
		on_release:root.initialize_view()
		pos_hint:{"center_x":0.02, "center_y":0.95}
		size_hint: 0.09,0.12

	Button:
		text: root.words
		on_release:root.adjust_button_1()
		pos_hint:{"center_x":0.9, "center_y":0.9}
		size_hint: 0.15,0.12
        canvas.after:
            Color:
                rgba: .5, .5, .5, 1
            Line:
                width: 2
                rectangle: self.x, self.y, self.width, self.height

    Button:
		text: "Tracking"
		on_release:root.start_tracking()
		pos_hint:{"center_x":0.9, "center_y":0.7}
		size_hint: 0.15,0.12
        canvas.after:
            Color:
                rgba: .5, .5, .5, 1
            Line:
                width: 2
                rectangle: self.x, self.y, self.width, self.height

	Label:
	    id: notice
	    pos_hint:{"center_y":0.95}
	    text: root.message
	    bold: True
	    font_size: 20
