<MenuButton@Button>:
	font_size: 30
	size_hint: 0.2,0.1


<MainLayout>:
	canvas.before:
		Color:
			rgba: 0,0,0,0
		Rectangle:
			size: self.size
			pos: self.pos

    Button:
		text: ""
		on_release:
		    root.change_view()
		    root.adjust_img()
		    #root.turn_on_top_down()
		pos_hint:{"center_x":0.02, "center_y":0.95}
		size_hint: 0.09,0.12

	Label:
	    id: notice
	    pos_hint:{"center_y":0.95}
	    text: root.message
	    bold: True
	    font_size: 20